/* Re-download the display fonts as local WOFF2 and regenerate fonts.css.
 *
 *   node prototype/fonts/refresh-fonts.mjs
 *
 * Needs network. Run it on a dev machine, commit the result, and the
 * venue box never touches a CDN. See README.md in this folder for why
 * that matters more than it sounds.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const OUT = path.dirname(fileURLToPath(import.meta.url));
const KEEP = new Set(["latin", "latin-ext"]);      // team names never need vietnamese
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
           "(KHTML, like Gecko) Chrome/120.0 Safari/537.36";

/* The families the board actually uses. Adding one here is the whole
   change — fonts.css is generated, never hand-edited. */
const QUERY = "family=Archivo+Black&family=Barlow+Condensed:wght@500;600;700&display=swap";

const cssRes = await fetch(`https://fonts.googleapis.com/css2?${QUERY}`, { headers: { "User-Agent": UA } });
if (!cssRes.ok) { console.error(`fetching the stylesheet failed: ${cssRes.status}`); process.exit(1); }
const css = await cssRes.text();

/* Google emits one @font-face per subset, each preceded by a /* subset *​/
   comment. That comment is the only place the subset name appears, so it
   is what we filter on. */
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
if (!blocks.length) { console.error("no @font-face blocks found — did the CSS format change?"); process.exit(1); }

const want = [];
for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const fam = /font-family:\s*'([^']+)'/.exec(block)[1];
  const wt = /font-weight:\s*(\d+)/.exec(block)[1];
  const url = /url\((https:[^)]+)\)/.exec(block)[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block)[1].trim();
  const slug = fam.toLowerCase().replace(/\s+/g, "-");
  want.push({ fam, wt, url, range, subset, file: `${slug}-${wt}-${subset}.woff2` });
}

let total = 0, failed = 0;
for (const w of want) {
  const res = await fetch(w.url, { headers: { "User-Agent": UA } });
  if (!res.ok) { console.error(`FAILED ${w.file}: ${res.status}`); failed++; continue; }
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(path.join(OUT, w.file), buf);
  total += buf.length;
  console.log(`  ${w.file}  ${(buf.length / 1024).toFixed(1)} KB`);
}

fs.writeFileSync(path.join(OUT, "fonts.css"), `/* GENERATED by refresh-fonts.mjs — do not hand-edit.
   Third Coast display fonts, bundled rather than linked. The venue box has
   no uplink; a Google Fonts <link> renders the whole board in Times New
   Roman there while looking perfect on a dev machine (handoff section 2).

   Subsets: latin + latin-ext only.
   font-display: block, not swap — a fallback flashing to Archivo Black on a
   TV nobody is standing at is worse than a beat of nothing. */

${want.map(w => `@font-face {
  font-family: '${w.fam}';
  font-style: normal;
  font-weight: ${w.wt};
  font-display: block;
  src: url('${w.file}') format('woff2');
  unicode-range: ${w.range};
}`).join("\n\n")}
`);

console.log(`\n${want.length - failed}/${want.length} faces, ${(total / 1024).toFixed(1)} KB total`);
if (failed) process.exit(1);
